{% set version = "0.0.3" %}

package:
  name: tcmarkers
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tcmarkers/tcmarkers-{{ version }}.tar.gz
  sha256: 2e31ee5bae5462b6d23b8902af748fc419792512c5893deb7d7e25ceb16a6385

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy

test:
  imports:
    - tcmarkers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/abrammer/tc_markers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:  Matplotib paths for Tropical Storm and Hurricane symbols

extra:
  recipe-maintainers:
    - raybellwaves
