{% set version = "0.0.5" %}

package:
  name: tcmarkers
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tcmarkers/tcmarkers-{{ version }}.tar.gz
  sha256: 1aa3f8ada18b415fc62d6be4b4941f4cb337ea7313ee41d57ded6a5a69245588

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.7
    - matplotlib-base
    - numpy

test:
  imports:
    - tcmarkers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/abrammer/tc_markers
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotib paths for Tropical Storm and Hurricane symbols

extra:
  recipe-maintainers:
    - raybellwaves
